### ISSUE TITLE
Multiple markers

### ISSUE THREAD

**Issue by dubmosphere** [rafu1987/medgooglemaps#1]
When adding multiple markers, only the location of the center of the map will be used for all of them. I could fix it declaring the locations array outside the loop and then push the location inside without reinitializing the locations array. Then the location you push should not take the latitude and longtitude from the flexform, but $marker->getLatitude() and $marker->getLongitude(), because a marker wants his location and not the location of the center of the map.

Greetings
Dub

**Comment by digitalgenossen** [comment]
Hi dubmosphere,

I´ve got the same problem here, but don´t understand how you got it solved :-(
Could you maybe post the code you changed as mentioned above? 
That be be great! 

Thank you very much in advance.

Best wishes,
Kai

**Comment by rafu1987** [comment]
Should be fixed now. I will upload a new TER version later. Thanks for reporting! :)
